/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duralex;

import static duralex.DuraLex.*;
//import static duralex.DuraLex.outl;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JTextField;


/**
 *
 * @author dizel
 */
public class Developer_helper extends javax.swing.JFrame {

    /**
     * Creates new form Developer_helper
     */
    public Developer_helper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nawigator = new javax.swing.JFileChooser();
        url = new javax.swing.JTextField();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        regex = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tekst = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        wynik = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(999, 999));
        setSize(new java.awt.Dimension(600, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        url.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("duralex/Bundle"); // NOI18N
        url.setText(bundle.getString("Developer_helper.url.text")); // NOI18N
        url.setDoubleBuffered(true);
        url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlActionPerformed(evt);
            }
        });
        url.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                urlKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                urlKeyReleased(evt);
            }
        });
        getContentPane().add(url, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setDividerLocation(311);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setFocusable(false);
        jSplitPane2.setOpaque(false);
        jSplitPane2.setRequestFocusEnabled(false);
        jSplitPane2.setVerifyInputWhenFocusTarget(false);

        jSplitPane1.setDividerLocation(99);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setFocusable(false);
        jSplitPane1.setRequestFocusEnabled(false);
        jSplitPane1.setVerifyInputWhenFocusTarget(false);

        regex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regex.setText(bundle.getString("Developer_helper.regex.text")); // NOI18N
        regex.setDoubleBuffered(true);
        regex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexActionPerformed(evt);
            }
        });
        regex.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                regexPropertyChange(evt);
            }
        });
        regex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regexKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regexKeyReleased(evt);
            }
        });
        jSplitPane1.setLeftComponent(regex);

        jScrollPane3.setBorder(null);
        jScrollPane3.setViewportBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane3.setEnabled(false);
        jScrollPane3.setFocusable(false);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setRequestFocusEnabled(false);
        jScrollPane3.setVerifyInputWhenFocusTarget(false);

        tekst.setContentType("rtf"); // NOI18N
        tekst.setEditorKit(null);
        tekst.setText(bundle.getString("Developer_helper.tekst.text")); // NOI18N
        tekst.setDoubleBuffered(true);
        tekst.setDragEnabled(true);
        tekst.setDropMode(javax.swing.DropMode.INSERT);
        tekst.setMinimumSize(new java.awt.Dimension(56, 10));
        tekst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tekstKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tekst);

        jSplitPane1.setRightComponent(jScrollPane3);

        jSplitPane2.setTopComponent(jSplitPane1);

        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(1000, 300));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(6, 23));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setRequestFocusEnabled(false);
        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        wynik.setEditable(false);
        wynik.setDoubleBuffered(true);
        wynik.setDropMode(javax.swing.DropMode.INSERT);
        wynik.setFocusCycleRoot(false);
        wynik.setFocusable(false);
        wynik.setMaximumSize(new java.awt.Dimension(1000, 300));
        wynik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wynikKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(wynik);

        jSplitPane2.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regexKeyReleased
        try{
            int r=0,t=0,c=0;
            pat = Pattern.compile(rgx=regex.getText());
            outl("pat zatwierdzony");
            mat = pat.matcher(txt=tekst.getText().replace("\n", ""));
            outl("mat zatwierdzony");
            tmp = "";
            while(  mat.find()  ){
                outl(r+++""+ ((mat.group().equals(" ")||mat.group().equals(""))?"":(mat.group()+"\n")));
                tmp+=(mat.group().equals(" ")||mat.group().equals(""))?"":(mat.group()+"\n");
                outl(t++);
                wynik.setText(tmp);
                outl(c++);
            }
            //wynik.setText(wnk=tmp);
        }catch(java.util.regex.PatternSyntaxException pse){
            wynik.setText(pse.getDescription());
        }catch (NullPointerException npe){
            wynik.setText("null pointer");
        }
    }//GEN-LAST:event_regexKeyReleased

    private void tekstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tekstKeyPressed
        save(evt,true);
        f5(evt);
    }//GEN-LAST:event_tekstKeyPressed

    private void wynikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wynikKeyPressed
        save(evt,true);
        f5(evt);
    }//GEN-LAST:event_wynikKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        save(evt,true);
        f5(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        f5(evt);
    }//GEN-LAST:event_formKeyReleased

    private void urlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlKeyReleased
        tekst.setText(DuraLex.getText(url.getText()));
    }//GEN-LAST:event_urlKeyReleased

    private void urlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlKeyPressed
        f5(evt);
    }//GEN-LAST:event_urlKeyPressed

    private void regexPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_regexPropertyChange

    }//GEN-LAST:event_regexPropertyChange

    private void regexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regexKeyPressed
            save(evt,true);
    }//GEN-LAST:event_regexKeyPressed

    private void regexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regexActionPerformed

    private void urlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlActionPerformed
    
    static String rgx="",txt="",tmp="",wnk="";
    static Pattern pat;
    static Matcher mat;
    static int count=0;
    int save(KeyEvent evt,boolean append){
        int apr=JFileChooser.ERROR_OPTION, of=-50,len=50;
        if(evt.isControlDown()){
            if(evt.getKeyCode()==KeyEvent.VK_S){try{
                
                String temp="";
                apr=nawigator.showSaveDialog(regex);
                FileWriter fw = new java.io.FileWriter(nawigator.getSelectedFile(),append);
                fw.write((temp+="\t<regex>\n"+rgx+"\n\t</regex>"));
                temp+=(txt="\t<text>\n"+txt+"\n\t</text>");
                fw.flush();
                //while((of+=len)<txt.length()&&of<len)fw.write(txt,of,len);
                fw.write(txt);
                fw.flush();
                wynik.setText(temp);
            }catch(IOException ioe){}
            }
            
            else if(evt.getKeyCode()==KeyEvent.VK_O){
            try {
                nawigator.showOpenDialog(regex);
                String temp="";
                FileReader fr;
                (fr=new FileReader(nawigator.getSelectedFile())).read(temp.toCharArray());
                tekst.setText(temp);
                        
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Developer_helper.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Developer_helper.class.getName()).log(Level.SEVERE, null, ex);
            }
            }}
        return apr;
    }        
    void f5(KeyEvent evt){
        if(evt.getKeyCode()==KeyEvent.VK_F5){
            if(evt.isShiftDown()){outl("SHIFT "+(evt.getKeyCode()==KeyEvent.VK_F5)+" "+evt.getSource().getClass().toGenericString());
            mat=pat.matcher(rgx);}
            else if(evt.isAltDown()){outl("ALT "+(evt.getKeyCode()==KeyEvent.VK_F5)+" "+evt.getSource().getClass().toGenericString());
            regex.revalidate();}
            else if(evt.isControlDown()){outl("CTRL "+(evt.getKeyCode()==KeyEvent.VK_F5)+" "+evt.getSource().getClass().toGenericString());
            regex.validate();}
            else {outl("f10");
                regex=new JTextField();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developer_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developer_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developer_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developer_helper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //@Override
        java.awt.EventQueue.invokeLater(() -> {
            (new Developer_helper()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private static javax.swing.JFileChooser nawigator;
    private static javax.swing.JTextField regex;
    private javax.swing.JEditorPane tekst;
    private javax.swing.JTextField url;
    private javax.swing.JTextPane wynik;
    // End of variables declaration//GEN-END:variables
}
